//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int Kisi_Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel_No1 { get; set; }
        public string Tel_No2 { get; set; }
        public string Mail { get; set; }
        public string Unvan { get; set; }
        public Nullable<int> Grup_ID { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
    }
}
